
/**
 * Utility to convert JSON strings to Go struct definitions.
 */

function toPascalCase(str: string): string {
  if (!str) return 'AutoGenerated';
  return str
    .replace(/[^a-z0-9]/gi, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') || 'AutoGenerated';
}

function getGoType(value: any, key: string, structs: string[]): string {
  if (value === null) return 'interface{}';
  
  const type = typeof value;
  
  if (type === 'string') return 'string';
  if (type === 'number') return Number.isInteger(value) ? 'int' : 'float64';
  if (type === 'boolean') return 'bool';
  
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}';
    const subType = getGoType(value[0], key, structs);
    return `[]${subType}`;
  }
  
  if (type === 'object') {
    const structName = toPascalCase(key);
    structs.push(generateStruct(value, structName, structs));
    return structName;
  }
  
  return 'interface{}';
}

function generateStruct(obj: any, name: string, structs: string[]): string {
  let result = `type ${name} struct {\n`;
  const keys = Object.keys(obj);
  
  for (const key of keys) {
    const goKey = toPascalCase(key);
    const goType = getGoType(obj[key], key, structs);
    result += `\t${goKey} ${goType} \`json:"${key}"\`\n`;
  }
  
  result += `}`;
  return result;
}

export function jsonToGo(jsonStr: string, rootName: string = 'Root'): string {
  try {
    const parsed = JSON.parse(jsonStr);
    if (typeof parsed !== 'object' || parsed === null) {
      return '// Error: Input must be a JSON object or array';
    }

    const structs: string[] = [];
    const mainStruct = generateStruct(parsed, toPascalCase(rootName), structs);
    
    // Reverse structs to show dependencies first or root first? Usually root first.
    // We filter unique structs by name to avoid duplicates if same key appears nested.
    const seen = new Set<string>();
    const uniqueStructs = [mainStruct, ...structs].filter(s => {
      const name = s.match(/type (\w+) struct/)?.[1];
      if (name && !seen.has(name)) {
        seen.add(name);
        return true;
      }
      return false;
    });

    return uniqueStructs.join('\n\n');
  } catch (e: any) {
    return `// Error: ${e.message}`;
  }
}
