/**
 * Utility to convert JSON strings to TypeScript interface or type definitions.
 */

export interface JsonToTsOptions {
  rootName?: string;
  useInterface?: boolean;
  optionalFields?: boolean;
}

function toPascalCase(str: string): string {
  if (!str) return 'AutoGenerated';
  return str
    .replace(/[^a-z0-9]/gi, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') || 'AutoGenerated';
}

function getTsType(value: any, key: string, types: string[], options: JsonToTsOptions, depth: number = 0): string {
  if (value === null) return 'any';
  
  const type = typeof value;
  
  if (type === 'string') return 'string';
  if (type === 'number') return 'number';
  if (type === 'boolean') return 'boolean';
  
  if (Array.isArray(value)) {
    if (value.length === 0) return 'any[]';
    // Try to get the type of the first element
    const subType = getTsType(value[0], key, types, options, depth);
    return `${subType}[]`;
  }
  
  if (type === 'object') {
    const typeName = toPascalCase(key);
    types.push(generateTsDefinition(value, typeName, types, options, 0));
    return typeName;
  }
  
  return 'any';
}

function generateTsDefinition(obj: any, name: string, types: string[], options: JsonToTsOptions, depth: number = 0): string {
  const { useInterface = true, optionalFields = false } = options;
  const indent = '  ';
  
  let result = useInterface ? `interface ${name} {\n` : `type ${name} = {\n`;
  
  const keys = Object.keys(obj);
  for (const key of keys) {
    const isOptional = optionalFields ? '?' : '';
    const tsType = getTsType(obj[key], key, types, options, depth + 1);
    result += `${indent}${key}${isOptional}: ${tsType};\n`;
  }
  
  result += `}`;
  return result;
}

export function jsonToTs(jsonStr: string, options: JsonToTsOptions = {}): string {
  const { rootName = 'Root' } = options;
  try {
    const parsed = JSON.parse(jsonStr);
    if (typeof parsed !== 'object' || parsed === null) {
      return '// Error: Input must be a JSON object or array';
    }

    const types: string[] = [];
    const mainType = generateTsDefinition(parsed, toPascalCase(rootName), types, options, 0);
    
    // Filter unique definitions by name
    const seen = new Set<string>();
    const allTypes = [mainType, ...types];
    const uniqueTypes = allTypes.filter(t => {
      const match = t.match(/(?:interface|type) (\w+)/);
      if (match) {
        const name = match[1];
        if (seen.has(name)) return false;
        seen.add(name);
        return true;
      }
      return true;
    });

    return uniqueTypes.join('\n\n');
  } catch (e: any) {
    return `// Error: ${e.message}`;
  }
}
