/**
 * Utility to convert JSON strings to Java Class definitions (POJOs).
 */

export interface JsonToJavaOptions {
  rootName?: string;
  packageName?: string;
  useJackson?: boolean;
  useLombok?: boolean;
}

function toPascalCase(str: string): string {
  if (!str) return 'AutoGenerated';
  return str
    .replace(/[^a-z0-9]/gi, ' ')
    .split(' ')
    .filter(word => word.length > 0)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') || 'AutoGenerated';
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function getJavaType(value: any, key: string, classes: string[], options: JsonToJavaOptions): string {
  if (value === null) return 'Object';
  
  const type = typeof value;
  
  if (type === 'string') return 'String';
  if (type === 'number') return Number.isInteger(value) ? 'Integer' : 'Double';
  if (type === 'boolean') return 'Boolean';
  
  if (Array.isArray(value)) {
    if (value.length === 0) return 'List<Object>';
    const subType = getJavaType(value[0], key, classes, options);
    return `List<${subType}>`;
  }
  
  if (type === 'object') {
    const className = classes.length === 0 ? toPascalCase(options.rootName || 'Root') : toPascalCase(key);
    classes.push(generateJavaClass(value, className, classes, options, false));
    return className;
  }
  
  return 'Object';
}

function generateJavaClass(obj: any, name: string, classes: string[], options: JsonToJavaOptions, isRoot: boolean): string {
  const { useJackson = false, useLombok = false } = options;
  const indent = '    ';
  
  let result = '';
  
  if (useLombok) {
    result += `@Data\n@NoArgsConstructor\n@AllArgsConstructor\n`;
  }
  
  result += `public class ${name} {\n`;
  
  const keys = Object.keys(obj);
  for (const key of keys) {
    const javaKey = toCamelCase(key);
    const javaType = getJavaType(obj[key], key, classes, options);
    
    if (useJackson) {
      result += `${indent}@JsonProperty("${key}")\n`;
    }
    
    result += `${indent}private ${javaType} ${javaKey};\n`;
  }
  
  // Add Getters/Setters if not using Lombok
  if (!useLombok) {
    for (const key of keys) {
      const javaKey = toCamelCase(key);
      const javaType = getJavaType(obj[key], key, classes, options);
      const pascalKey = toPascalCase(key);
      
      // Getter
      result += `\n${indent}public ${javaType} get${pascalKey}() {\n`;
      result += `${indent}${indent}return ${javaKey};\n`;
      result += `${indent}}\n`;
      
      // Setter
      result += `\n${indent}public void set${pascalKey}(${javaType} ${javaKey}) {\n`;
      result += `${indent}${indent}this.${javaKey} = ${javaKey};\n`;
      result += `${indent}}\n`;
    }
  }
  
  result += `}`;
  return result;
}

export function jsonToJava(jsonStr: string, options: JsonToJavaOptions = {}): string {
  const { rootName = 'Root', packageName = 'com.example.generated' } = options;
  try {
    const parsed = JSON.parse(jsonStr);
    if (typeof parsed !== 'object' || parsed === null) {
      return '// Error: Input must be a JSON object or array';
    }

    const classes: string[] = [];
    const mainClass = generateJavaClass(parsed, toPascalCase(rootName), classes, options, true);
    
    let fullOutput = '';
    if (packageName) {
      fullOutput += `package ${packageName};\n\n`;
    }
    
    // Add Imports
    const imports = new Set<string>();
    if (jsonStr.includes('[')) imports.add('import java.util.List;');
    if (options.useJackson) imports.add('import com.fasterxml.jackson.annotation.JsonProperty;');
    if (options.useLombok) {
      imports.add('import lombok.Data;');
      imports.add('import lombok.NoArgsConstructor;');
      imports.add('import lombok.AllArgsConstructor;');
    }
    
    if (imports.size > 0) {
      fullOutput += Array.from(imports).sort().join('\n') + '\n\n';
    }

    // Filter unique classes by name to avoid duplicates
    const seen = new Set<string>();
    const allGenerated = [mainClass, ...classes];
    const uniqueClasses = allGenerated.filter(c => {
      const match = c.match(/public class (\w+)/);
      if (match) {
        const name = match[1];
        if (seen.has(name)) return false;
        seen.add(name);
        return true;
      }
      return true;
    });

    fullOutput += uniqueClasses.join('\n\n');
    return fullOutput;
  } catch (e: any) {
    return `// Error: ${e.message}`;
  }
}
