
/**
 * Utility to convert JSON strings to Go struct definitions.
 */

function toPascalCase(str: string): string {
  if (!str) return 'AutoGenerated';
  return str
    .replace(/[^a-z0-9]/gi, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') || 'AutoGenerated';
}

function getGoType(value: any, key: string, structs: string[], inline: boolean, depth: number = 0): string {
  if (value === null) return 'interface{}';
  
  const type = typeof value;
  
  if (type === 'string') return 'string';
  if (type === 'number') return Number.isInteger(value) ? 'int' : 'float64';
  if (type === 'boolean') return 'bool';
  
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}';
    const subType = getGoType(value[0], key, structs, inline, depth);
    return `[]${subType}`;
  }
  
  if (type === 'object') {
    if (inline && depth > 0) {
      return generateStruct(value, '', structs, inline, depth);
    } else {
      const structName = toPascalCase(key);
      structs.push(generateStruct(value, structName, structs, inline, depth));
      return structName;
    }
  }
  
  return 'interface{}';
}

function generateStruct(obj: any, name: string, structs: string[], inline: boolean, depth: number = 0): string {
  const indent = '\t'.repeat(depth + 1);
  const closingIndent = '\t'.repeat(depth);
  let result = name ? `type ${name} struct {\n` : `struct {\n`;
  const keys = Object.keys(obj);
  
  for (const key of keys) {
    const goKey = toPascalCase(key);
    const goType = getGoType(obj[key], key, structs, inline, depth + 1);
    result += `${indent}${goKey} ${goType} \`json:"${key}"\`\n`;
  }
  
  result += `${closingIndent}}`;
  return result;
}

export interface JsonToGoOptions {
  rootName?: string;
  inline?: boolean;
}

export function jsonToGo(jsonStr: string, options: JsonToGoOptions = {}): string {
  const { rootName = 'Root', inline = false } = options;
  try {
    const parsed = JSON.parse(jsonStr);
    if (typeof parsed !== 'object' || parsed === null) {
      return '// Error: Input must be a JSON object or array';
    }

    const structs: string[] = [];
    // depth 0 for the root
    const mainStruct = generateStruct(parsed, toPascalCase(rootName), structs, inline, 0);
    
    // Filter unique structs by name to avoid duplicates if same key appears nested.
    const seen = new Set<string>();
    const uniqueStructs = [mainStruct, ...structs].filter(s => {
      const nameMatch = s.match(/type (\w+) struct/);
      if (nameMatch) {
        const name = nameMatch[1];
        if (seen.has(name)) return false;
        seen.add(name);
        return true;
      }
      return true; // Root or non-named structs (though root usually has name)
    });

    return uniqueStructs.join('\n\n');
  } catch (e: any) {
    return `// Error: ${e.message}`;
  }
}
