/**
 * Utility to convert JSON strings to Rust struct definitions with Serde attributes.
 */

function toPascalCase(str: string): string {
  if (!str) return 'AutoGenerated';
  return str
    .replace(/[^a-z0-9]/gi, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') || 'AutoGenerated';
}

function toSnakeCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[^a-z0-9]/gi, '_')
    .toLowerCase()
    .replace(/^_+|_+$/g, '');
}

function getRustType(value: any, key: string, structs: string[], options: JsonToRustOptions, depth: number = 0): string {
  if (value === null) return 'Option<serde_json::Value>';
  
  const type = typeof value;
  
  if (type === 'string') return 'String';
  if (type === 'number') return Number.isInteger(value) ? 'i64' : 'f64';
  if (type === 'boolean') return 'bool';
  
  if (Array.isArray(value)) {
    if (value.length === 0) return 'Vec<serde_json::Value>';
    const subType = getRustType(value[0], key, structs, options, depth);
    return `Vec<${subType}>`;
  }
  
  if (type === 'object') {
    const structName = toPascalCase(key);
    structs.push(generateRustStruct(value, structName, structs, options, 0));
    return structName;
  }
  
  return 'serde_json::Value';
}

function generateRustStruct(obj: any, name: string, structs: string[], options: JsonToRustOptions, depth: number = 0): string {
  const { isPublic = true, derives = 'Default, Debug, Serialize, Deserialize' } = options;
  const visibility = isPublic ? 'pub ' : '';
  const indent = '    ';
  
  let result = `#[derive(${derives})]\n`;
  result += `${visibility}struct ${name} {\n`;
  
  const keys = Object.keys(obj);
  for (const key of keys) {
    const rustKey = toSnakeCase(key);
    const rustType = getRustType(obj[key], key, structs, options, depth + 1);
    
    // Add serde rename if the keys don't match exactly
    if (rustKey !== key) {
      result += `${indent}#[serde(rename = "${key}")]\n`;
    }
    
    result += `${indent}${visibility}${rustKey}: ${rustType},\n`;
  }
  
  result += `}`;
  return result;
}

export interface JsonToRustOptions {
  rootName?: string;
  isPublic?: boolean;
  derives?: string;
}

export function jsonToRust(jsonStr: string, options: JsonToRustOptions = {}): string {
  const { rootName = 'Root' } = options;
  try {
    const parsed = JSON.parse(jsonStr);
    if (typeof parsed !== 'object' || parsed === null) {
      return '// Error: Input must be a JSON object or array';
    }

    const structs: string[] = [];
    const mainStruct = generateRustStruct(parsed, toPascalCase(rootName), structs, options, 0);
    
    // Filter unique structs by name
    const seen = new Set<string>();
    const allStructs = [mainStruct, ...structs];
    const uniqueStructs = allStructs.filter(s => {
      const nameMatch = s.match(/struct (\w+)/);
      if (nameMatch) {
        const name = nameMatch[1];
        if (seen.has(name)) return false;
        seen.add(name);
        return true;
      }
      return true;
    });

    return uniqueStructs.join('\n\n');
  } catch (e: any) {
    return `// Error: ${e.message}`;
  }
}
