import { Hash, KeyRound, Fingerprint, Braces, Terminal, CodeXml, LayoutPanelLeft, Palette, ScrollText, Code2, Link as LinkIcon, Binary, Hexagon } from 'lucide-react';

export interface Tool {
  id: string;
  nameKey: string;
  descriptionKey: string;
  href: string;
  icon: string;
  category: 'Encoding' | 'Security' | 'Formatting' | 'Generators' | 'Conversion';
}

export const TOOLS: Tool[] = [
  {
    id: 'base64-encode',
    nameKey: 'tools.base64_encode.name',
    descriptionKey: 'tools.base64_encode.description',
    href: '/base64/encode',
    icon: 'Hash',
    category: 'Encoding',
  },
  {
    id: 'base64-decode',
    nameKey: 'tools.base64_decode.name',
    descriptionKey: 'tools.base64_decode.description',
    href: '/base64/decode',
    icon: 'Hash',
    category: 'Encoding',
  },
  {
    id: 'binary-encode',
    nameKey: 'tools.binary_encode.name',
    descriptionKey: 'tools.binary_encode.description',
    href: '/binary/encode',
    icon: 'Binary',
    category: 'Encoding',
  },
  {
    id: 'binary-decode',
    nameKey: 'tools.binary_decode.name',
    descriptionKey: 'tools.binary_decode.description',
    href: '/binary/decode',
    icon: 'Binary',
    category: 'Encoding',
  },
  {
    id: 'hex-encode',
    nameKey: 'tools.hex_encode.name',
    descriptionKey: 'tools.hex_encode.description',
    href: '/hex/encode',
    icon: 'Hexagon',
    category: 'Encoding',
  },
  {
    id: 'hex-decode',
    nameKey: 'tools.hex_decode.name',
    descriptionKey: 'tools.hex_decode.description',
    href: '/hex/decode',
    icon: 'Hexagon',
    category: 'Encoding',
  },
  {
    id: 'url-encode',
    nameKey: 'tools.url_encode.name',
    descriptionKey: 'tools.url_encode.description',
    href: '/url/encode',
    icon: 'LinkIcon',
    category: 'Encoding',
  },
  {
    id: 'url-decode',
    nameKey: 'tools.url_decode.name',
    descriptionKey: 'tools.url_decode.description',
    href: '/url/decode',
    icon: 'LinkIcon',
    category: 'Encoding',
  },
  {
    id: 'html-encode',
    nameKey: 'tools.html_encode.name',
    descriptionKey: 'tools.html_encode.description',
    href: '/html/encode',
    icon: 'CodeXml',
    category: 'Encoding',
  },
  {
    id: 'html-decode',
    nameKey: 'tools.html_decode.name',
    descriptionKey: 'tools.html_decode.description',
    href: '/html/decode',
    icon: 'CodeXml',
    category: 'Encoding',
  },
  {
    id: 'json-formatter',
    nameKey: 'tools.json_formatter.name',
    descriptionKey: 'tools.json_formatter.description',
    href: '/json/formatter',
    icon: 'Braces',
    category: 'Formatting',
  },
  {
    id: 'js-formatter',
    nameKey: 'tools.js_formatter.name',
    descriptionKey: 'tools.js_formatter.description',
    href: '/javascript/formatter',
    icon: 'ScrollText',
    category: 'Formatting',
  },
  {
    id: 'ts-formatter',
    nameKey: 'tools.ts_formatter.name',
    descriptionKey: 'tools.ts_formatter.description',
    href: '/typescript/formatter',
    icon: 'Code2',
    category: 'Formatting',
  },
  {
    id: 'xml-formatter',
    nameKey: 'tools.xml_formatter.name',
    descriptionKey: 'tools.xml_formatter.description',
    href: '/xml/formatter',
    icon: 'CodeXml',
    category: 'Formatting',
  },
  {
    id: 'html-formatter',
    nameKey: 'tools.html_formatter.name',
    descriptionKey: 'tools.html_formatter.description',
    href: '/html/formatter',
    icon: 'LayoutPanelLeft',
    category: 'Formatting',
  },
  {
    id: 'css-formatter',
    nameKey: 'tools.css_formatter.name',
    descriptionKey: 'tools.css_formatter.description',
    href: '/css/formatter',
    icon: 'Palette',
    category: 'Formatting',
  },
  {
    id: 'json-to-go',
    nameKey: 'tools.json_to_go.name',
    descriptionKey: 'tools.json_to_go.description',
    href: '/json/to-golang-struct',
    icon: 'Terminal',
    category: 'Conversion',
  },
  {
    id: 'uuid-v4',
    nameKey: 'tools.uuid_v4.name',
    descriptionKey: 'tools.uuid_v4.description',
    href: '/uuid/v4',
    icon: 'Fingerprint',
    category: 'Generators',
  },
  {
    id: 'uuid-v1',
    nameKey: 'tools.uuid_v1.name',
    descriptionKey: 'tools.uuid_v1.description',
    href: '/uuid/v1',
    icon: 'Fingerprint',
    category: 'Generators',
  },
  {
    id: 'uuid-v7',
    nameKey: 'tools.uuid_v7.name',
    descriptionKey: 'tools.uuid_v7.description',
    href: '/uuid/v7',
    icon: 'Fingerprint',
    category: 'Generators',
  },
  {
    id: 'guid',
    nameKey: 'tools.guid.name',
    descriptionKey: 'tools.guid.description',
    href: '/guid',
    icon: 'Fingerprint',
    category: 'Generators',
  }
];
