import { Hash, KeyRound, Fingerprint, Braces, Terminal, CodeXml, LayoutPanelLeft, Palette, ScrollText, Code2, Link as LinkIcon, Binary, Hexagon, ShieldCheck, FileKey, Lock, ShieldAlert, Zap, Activity, ShieldEllipsis, ShieldPlus, FileBadge, ShieldHalf, RefreshCw, ArrowRightLeft, FileSearch, EyeOff, Wand2, FileJson, FileText, Table2, FileSpreadsheet, Cpu, Coffee } from 'lucide-react';

export interface Tool {
  id: string;
  nameKey: string;
  descriptionKey: string;
  href: string;
  icon: string;
  category: 'Encoding' | 'Encryption' | 'Security' | 'Formatting' | 'Generators' | 'Conversion' | 'Hashing' | 'Passwords' | 'Obfuscation';
}

export const TOOLS: Tool[] = [
  {
    id: 'password-generator',
    nameKey: 'tools.password_generator.name',
    descriptionKey: 'tools.password_generator.description',
    href: '/passwords/generator',
    icon: 'RefreshCw',
    category: 'Passwords',
  },
  {
    id: 'password-strength',
    nameKey: 'tools.password_strength.name',
    descriptionKey: 'tools.password_strength.description',
    href: '/passwords/strength',
    icon: 'ShieldHalf',
    category: 'Passwords',
  },
  {
    id: 'password-compare',
    nameKey: 'tools.password_compare.name',
    descriptionKey: 'tools.password_compare.description',
    href: '/passwords/compare',
    icon: 'KeyRound',
    category: 'Passwords',
  },
  {
    id: 'password-hash',
    nameKey: 'tools.password_hash.name',
    descriptionKey: 'tools.password_hash.description',
    href: '/passwords/hash',
    icon: 'Lock',
    category: 'Passwords',
  },
  {
    id: 'random-key-gen',
    nameKey: 'tools.random_key.name',
    descriptionKey: 'tools.random_key.description',
    href: '/generators/random-key',
    icon: 'KeyRound',
    category: 'Generators',
  },
  {
    id: 'secure-token-gen',
    nameKey: 'tools.secure_token.name',
    descriptionKey: 'tools.secure_token.description',
    href: '/generators/secure-token',
    icon: 'Zap',
    category: 'Generators',
  },
  {
    id: 'crc32-checksum',
    nameKey: 'tools.crc32.name',
    descriptionKey: 'tools.crc32.description',
    href: '/hashing/crc32',
    icon: 'FileSearch',
    category: 'Hashing',
  },
  {
    id: 'adler32-checksum',
    nameKey: 'tools.adler32.name',
    descriptionKey: 'tools.adler32.description',
    href: '/hashing/adler32',
    icon: 'FileSearch',
    category: 'Hashing',
  },
  {
    id: 'text-obfuscator',
    nameKey: 'tools.text_obfuscator.name',
    descriptionKey: 'tools.text_obfuscator.description',
    href: '/obfuscation/text',
    icon: 'EyeOff',
    category: 'Obfuscation',
  },
  {
    id: 'js-obfuscator',
    nameKey: 'tools.js_obfuscator.name',
    descriptionKey: 'tools.js_obfuscator.description',
    href: '/obfuscation/javascript',
    icon: 'ShieldAlert',
    category: 'Obfuscation',
  },
  {
    id: 'rot13-tool',
    nameKey: 'tools.rot13.name',
    descriptionKey: 'tools.rot13.description',
    href: '/obfuscation/rot13',
    icon: 'RefreshCw',
    category: 'Obfuscation',
  },
  {
    id: 'base64-encode',
    nameKey: 'tools.base64_encode.name',
    descriptionKey: 'tools.base64_encode.description',
    href: '/base64/encode',
    icon: 'Hash',
    category: 'Encoding',
  },
  {
    id: 'base64-decode',
    nameKey: 'tools.base64_decode.name',
    descriptionKey: 'tools.base64_decode.description',
    href: '/base64/decode',
    icon: 'Hash',
    category: 'Encoding',
  },
  {
    id: 'binary-encode',
    nameKey: 'tools.binary_encode.name',
    descriptionKey: 'tools.binary_encode.description',
    href: '/binary/encode',
    icon: 'Binary',
    category: 'Encoding',
  },
  {
    id: 'binary-decode',
    nameKey: 'tools.binary_decode.name',
    descriptionKey: 'tools.binary_decode.description',
    href: '/binary/decode',
    icon: 'Binary',
    category: 'Encoding',
  },
  {
    id: 'hex-encode',
    nameKey: 'tools.hex_encode.name',
    descriptionKey: 'tools.hex_encode.description',
    href: '/hex/encode',
    icon: 'Hexagon',
    category: 'Encoding',
  },
  {
    id: 'hex-decode',
    nameKey: 'tools.hex_decode.name',
    descriptionKey: 'tools.hex_decode.description',
    href: '/hex/decode',
    icon: 'Hexagon',
    category: 'Encoding',
  },
  {
    id: 'url-encode',
    nameKey: 'tools.url_encode.name',
    descriptionKey: 'tools.url_encode.description',
    href: '/url/encode',
    icon: 'LinkIcon',
    category: 'Encoding',
  },
  {
    id: 'url-decode',
    nameKey: 'tools.url_decode.name',
    descriptionKey: 'tools.url_decode.description',
    href: '/url/decode',
    icon: 'LinkIcon',
    category: 'Encoding',
  },
  {
    id: 'html-encode',
    nameKey: 'tools.html_encode.name',
    descriptionKey: 'tools.html_encode.description',
    href: '/html/encode',
    icon: 'CodeXml',
    category: 'Encoding',
  },
  {
    id: 'html-decode',
    nameKey: 'tools.html_decode.name',
    descriptionKey: 'tools.html_decode.description',
    href: '/html/decode',
    icon: 'CodeXml',
    category: 'Encoding',
  },
  {
    id: 'md5-hash',
    nameKey: 'tools.md5.name',
    descriptionKey: 'tools.md5.description',
    href: '/hashing/md5',
    icon: 'Fingerprint',
    category: 'Hashing',
  },
  {
    id: 'sha1-hash',
    nameKey: 'tools.sha1.name',
    descriptionKey: 'tools.sha1.description',
    href: '/hashing/sha1',
    icon: 'Fingerprint',
    category: 'Hashing',
  },
  {
    id: 'sha256-hash',
    nameKey: 'tools.sha256.name',
    descriptionKey: 'tools.sha256.description',
    href: '/hashing/sha256',
    icon: 'Fingerprint',
    category: 'Hashing',
  },
  {
    id: 'sha512-hash',
    nameKey: 'tools.sha512.name',
    descriptionKey: 'tools.sha512.description',
    href: '/hashing/sha512',
    icon: 'Fingerprint',
    category: 'Hashing',
  },
  {
    id: 'sha3-hash',
    nameKey: 'tools.sha3.name',
    descriptionKey: 'tools.sha3.description',
    href: '/hashing/sha3',
    icon: 'Fingerprint',
    category: 'Hashing',
  },
  {
    id: 'bcrypt-hash',
    nameKey: 'tools.bcrypt.name',
    descriptionKey: 'tools.bcrypt.description',
    href: '/hashing/bcrypt',
    icon: 'Lock',
    category: 'Hashing',
  },
  {
    id: 'argon2-hash',
    nameKey: 'tools.argon2.name',
    descriptionKey: 'tools.argon2.description',
    href: '/hashing/argon2',
    icon: 'Lock',
    category: 'Hashing',
  },
  {
    id: 'pbkdf2-hash',
    nameKey: 'tools.pbkdf2.name',
    descriptionKey: 'tools.pbkdf2.description',
    href: '/hashing/pbkdf2',
    icon: 'Lock',
    category: 'Hashing',
  },
  {
    id: 'hmac-sha1',
    nameKey: 'tools.hmac_sha1.name',
    descriptionKey: 'tools.hmac_sha1.description',
    href: '/hashing/hmac-sha1',
    icon: 'KeyRound',
    category: 'Hashing',
  },
  {
    id: 'hmac-sha256',
    nameKey: 'tools.hmac_sha256.name',
    descriptionKey: 'tools.hmac_sha256.description',
    href: '/hashing/hmac-sha256',
    icon: 'KeyRound',
    category: 'Hashing',
  },
  {
    id: 'hmac-sha512',
    nameKey: 'tools.hmac_sha512.name',
    descriptionKey: 'tools.hmac_sha512.description',
    href: '/hashing/hmac-sha512',
    icon: 'KeyRound',
    category: 'Hashing',
  },
  {
    id: 'aes-encrypt',
    nameKey: 'tools.aes_encrypt.name',
    descriptionKey: 'tools.aes_encrypt.description',
    href: '/security/aes/encrypt',
    icon: 'Lock',
    category: 'Encryption',
  },
  {
    id: 'aes-decrypt',
    nameKey: 'tools.aes_decrypt.name',
    descriptionKey: 'tools.aes_decrypt.description',
    href: '/security/aes/decrypt',
    icon: 'ShieldPlus',
    category: 'Encryption',
  },
  {
    id: 'des-encrypt',
    nameKey: 'tools.des_encrypt.name',
    descriptionKey: 'tools.des_encrypt.description',
    href: '/security/des/encrypt',
    icon: 'Lock',
    category: 'Encryption',
  },
  {
    id: 'des-decrypt',
    nameKey: 'tools.des_decrypt.name',
    descriptionKey: 'tools.des_decrypt.description',
    href: '/security/des/decrypt',
    icon: 'ShieldPlus',
    category: 'Encryption',
  },
  {
    id: '3des-encrypt',
    nameKey: 'tools.3des_encrypt.name',
    descriptionKey: 'tools.3des_encrypt.description',
    href: '/security/3des/encrypt',
    icon: 'Lock',
    category: 'Encryption',
  },
  {
    id: '3des-decrypt',
    nameKey: 'tools.3des_decrypt.name',
    descriptionKey: 'tools.3des_decrypt.description',
    href: '/security/3des/decrypt',
    icon: 'ShieldPlus',
    category: 'Encryption',
  },
  {
    id: 'chacha20-encrypt',
    nameKey: 'tools.chacha20_encrypt.name',
    descriptionKey: 'tools.chacha20_encrypt.description',
    href: '/security/chacha20/encrypt',
    icon: 'Zap',
    category: 'Encryption',
  },
  {
    id: 'chacha20-decrypt',
    nameKey: 'tools.chacha20_decrypt.name',
    descriptionKey: 'tools.chacha20_decrypt.description',
    href: '/security/chacha20/decrypt',
    icon: 'ShieldPlus',
    category: 'Encryption',
  },
  {
    id: 'rsa-encrypt',
    nameKey: 'tools.rsa_encrypt.name',
    descriptionKey: 'tools.rsa_encrypt.description',
    href: '/security/rsa/encrypt',
    icon: 'ShieldCheck',
    category: 'Encryption',
  },
  {
    id: 'rsa-decrypt',
    nameKey: 'tools.rsa_decrypt.name',
    descriptionKey: 'tools.rsa_decrypt.description',
    href: '/security/rsa/decrypt',
    icon: 'ShieldCheck',
    category: 'Encryption',
  },
  {
    id: 'rsa-sign',
    nameKey: 'tools.rsa_sign.name',
    descriptionKey: 'tools.rsa_sign.description',
    href: '/security/rsa/sign',
    icon: 'ShieldCheck',
    category: 'Encryption',
  },
  {
    id: 'rsa-verify',
    nameKey: 'tools.rsa_verify.name',
    descriptionKey: 'tools.rsa_verify.description',
    href: '/security/rsa/verify',
    icon: 'ShieldCheck',
    category: 'Encryption',
  },
  {
    id: 'pgp-encrypt',
    nameKey: 'tools.pgp_encrypt.name',
    descriptionKey: 'tools.pgp_encrypt.description',
    href: '/security/pgp/encrypt',
    icon: 'ShieldEllipsis',
    category: 'Encryption',
  },
  {
    id: 'pgp-decrypt',
    nameKey: 'tools.pgp_decrypt.name',
    descriptionKey: 'tools.pgp_decrypt.description',
    href: '/security/pgp/decrypt',
    icon: 'ShieldEllipsis',
    category: 'Encryption',
  },
  {
    id: 'pgp-sign',
    nameKey: 'tools.pgp_sign.name',
    descriptionKey: 'tools.pgp_sign.description',
    href: '/security/pgp/sign',
    icon: 'ShieldEllipsis',
    category: 'Encryption',
  },
  {
    id: 'pgp-verify',
    nameKey: 'tools.pgp_verify.name',
    descriptionKey: 'tools.pgp_verify.description',
    href: '/security/pgp/verify',
    icon: 'ShieldEllipsis',
    category: 'Encryption',
  },
  {
    id: 'ecc-sign',
    nameKey: 'tools.ecc_sign.name',
    descriptionKey: 'tools.ecc_sign.description',
    href: '/security/ecc/sign',
    icon: 'Activity',
    category: 'Security',
  },
  {
    id: 'ecc-verify',
    nameKey: 'tools.ecc_verify.name',
    descriptionKey: 'tools.ecc_verify.description',
    href: '/security/ecc/verify',
    icon: 'Activity',
    category: 'Security',
  },
  {
    id: 'jwt-encode',
    nameKey: 'tools.jwt_encode.name',
    descriptionKey: 'tools.jwt_encode.description',
    href: '/security/jwt/encode',
    icon: 'KeyRound',
    category: 'Security',
  },
  {
    id: 'jwt-decode',
    nameKey: 'tools.jwt_decode.name',
    descriptionKey: 'tools.jwt_decode.description',
    href: '/security/jwt/decode',
    icon: 'KeyRound',
    category: 'Security',
  },
  {
    id: 'jwt-verify',
    nameKey: 'tools.jwt_verify.name',
    descriptionKey: 'tools.jwt_verify.description',
    href: '/security/jwt/verify',
    icon: 'KeyRound',
    category: 'Security',
  },
  {
    id: 'certificate-decode',
    nameKey: 'tools.certificate_decode.name',
    descriptionKey: 'tools.certificate_decode.description',
    href: '/security/certificate/decode',
    icon: 'FileBadge',
    category: 'Security',
  },
  {
    id: 'csr-decode',
    nameKey: 'tools.csr_decode.name',
    descriptionKey: 'tools.csr_decode.description',
    href: '/security/csr/decode',
    icon: 'FileBadge',
    category: 'Security',
  },
  {
    id: 'pem-der-converter',
    nameKey: 'tools.pem_der_converter.name',
    descriptionKey: 'tools.pem_der_converter.description',
    href: '/security/pem-der-converter',
    icon: 'ArrowRightLeft',
    category: 'Security',
  },
  {
    id: 'asn1-inspector',
    nameKey: 'tools.asn1.name',
    descriptionKey: 'tools.asn1.description',
    href: '/security/asn1',
    icon: 'FileKey',
    category: 'Security',
  },
  {
    id: 'jose-studio',
    nameKey: 'tools.jose.name',
    descriptionKey: 'tools.jose.description',
    href: '/security/jose',
    icon: 'KeyRound',
    category: 'Security',
  },
  {
    id: 'openpgp-gen',
    nameKey: 'tools.openpgp.name',
    descriptionKey: 'tools.openpgp.description',
    href: '/security/openpgp',
    icon: 'Lock',
    category: 'Security',
  },
  {
    id: 'cose-cbor',
    nameKey: 'tools.cose.name',
    descriptionKey: 'tools.cose.description',
    href: '/security/cose',
    icon: 'ShieldAlert',
    category: 'Security',
  },
  {
    id: 'spki-formatter',
    nameKey: 'tools.spki.name',
    descriptionKey: 'tools.spki.description',
    href: '/security/spki',
    icon: 'Fingerprint',
    category: 'Security',
  },
  {
    id: 'pkcs-p1',
    nameKey: 'tools.pkcs_p1.name',
    descriptionKey: 'tools.pkcs_p1.description',
    href: '/pkcs/p1',
    icon: 'ShieldCheck',
    category: 'Security',
  },
  {
    id: 'pkcs-p7',
    nameKey: 'tools.pkcs_p7.name',
    descriptionKey: 'tools.pkcs_p7.description',
    href: '/pkcs/p7',
    icon: 'ShieldCheck',
    category: 'Security',
  },
  {
    id: 'pkcs-p8',
    nameKey: 'tools.pkcs_p8.name',
    descriptionKey: 'tools.pkcs_p8.description',
    href: '/pkcs/p8',
    icon: 'ShieldCheck',
    category: 'Security',
  },
  {
    id: 'pkcs-p10',
    nameKey: 'tools.pkcs_p10.name',
    descriptionKey: 'tools.pkcs_p10.description',
    href: '/pkcs/p10',
    icon: 'FileBadge',
    category: 'Security',
  },
  {
    id: 'pkcs-p12',
    nameKey: 'tools.pkcs_p12.name',
    descriptionKey: 'tools.pkcs_p12.description',
    href: '/pkcs/p12',
    icon: 'Lock',
    category: 'Security',
  },
  {
    id: 'pkcs-x509',
    nameKey: 'tools.pkcs_x509.name',
    descriptionKey: 'tools.pkcs_x509.description',
    href: '/security/x509',
    icon: 'FileBadge',
    category: 'Security',
  },
  {
    id: 'json-formatter',
    nameKey: 'tools.json_formatter.name',
    descriptionKey: 'tools.json_formatter.description',
    href: '/json/formatter',
    icon: 'Braces',
    category: 'Formatting',
  },
  {
    id: 'js-formatter',
    nameKey: 'tools.js_formatter.name',
    descriptionKey: 'tools.js_formatter.description',
    href: '/javascript/formatter',
    icon: 'ScrollText',
    category: 'Formatting',
  },
  {
    id: 'ts-formatter',
    nameKey: 'tools.ts_formatter.name',
    descriptionKey: 'tools.ts_formatter.description',
    href: '/typescript/formatter',
    icon: 'Code2',
    category: 'Formatting',
  },
  {
    id: 'xml-formatter',
    nameKey: 'tools.xml_formatter.name',
    descriptionKey: 'tools.xml_formatter.description',
    href: '/xml/formatter',
    icon: 'CodeXml',
    category: 'Formatting',
  },
  {
    id: 'html-formatter',
    nameKey: 'tools.html_formatter.name',
    descriptionKey: 'tools.html_formatter.description',
    href: '/html/formatter',
    icon: 'LayoutPanelLeft',
    category: 'Formatting',
  },
  {
    id: 'css-formatter',
    nameKey: 'tools.css_formatter.name',
    descriptionKey: 'tools.css_formatter.description',
    href: '/css/formatter',
    icon: 'Palette',
    category: 'Formatting',
  },
  {
    id: 'json-to-go',
    nameKey: 'tools.json_to_go.name',
    descriptionKey: 'tools.json_to_go.description',
    href: '/json/to-golang-struct',
    icon: 'Terminal',
    category: 'Conversion',
  },
  {
    id: 'json-to-rust',
    nameKey: 'tools.json_to_rust.name',
    descriptionKey: 'tools.json_to_rust.description',
    href: '/json/to-rust-struct',
    icon: 'Cpu',
    category: 'Conversion',
  },
  {
    id: 'json-to-ts',
    nameKey: 'tools.json_to_ts.name',
    descriptionKey: 'tools.json_to_ts.description',
    href: '/json/to-typescript',
    icon: 'Code2',
    category: 'Conversion',
  },
  {
    id: 'json-to-java',
    nameKey: 'tools.json_to_java.name',
    descriptionKey: 'tools.json_to_java.description',
    href: '/json/to-java-class',
    icon: 'Coffee',
    category: 'Conversion',
  },
  {
    id: 'json-to-yaml',
    nameKey: 'tools.json_to_yaml.name',
    descriptionKey: 'tools.json_to_yaml.description',
    href: '/json/to-yaml',
    icon: 'FileJson',
    category: 'Conversion',
  },
  {
    id: 'yaml-to-json',
    nameKey: 'tools.yaml_to_json.name',
    descriptionKey: 'tools.yaml_to_json.description',
    href: '/yaml/to-json',
    icon: 'FileText',
    category: 'Conversion',
  },
  {
    id: 'toml-to-json',
    nameKey: 'tools.toml_to_json.name',
    descriptionKey: 'tools.toml_to_json.description',
    href: '/toml/to-json',
    icon: 'FileText',
    category: 'Conversion',
  },
  {
    id: 'json-to-toml',
    nameKey: 'tools.json_to_toml.name',
    descriptionKey: 'tools.json_to_toml.description',
    href: '/json/to-toml',
    icon: 'Braces',
    category: 'Conversion',
  },
  {
    id: 'xml-to-json',
    nameKey: 'tools.xml_to_json.name',
    descriptionKey: 'tools.xml_to_json.description',
    href: '/xml/to-json',
    icon: 'CodeXml',
    category: 'Conversion',
  },
  {
    id: 'json-to-xml',
    nameKey: 'tools.json_to_xml.name',
    descriptionKey: 'tools.json_to_xml.description',
    href: '/json/to-xml',
    icon: 'Braces',
    category: 'Conversion',
  },
  {
    id: 'csv-to-json',
    nameKey: 'tools.csv_to_json.name',
    descriptionKey: 'tools.csv_to_json.description',
    href: '/csv/to-json',
    icon: 'Table2',
    category: 'Conversion',
  },
  {
    id: 'json-to-csv',
    nameKey: 'tools.json_to_csv.name',
    descriptionKey: 'tools.json_to_csv.description',
    href: '/json/to-csv',
    icon: 'FileSpreadsheet',
    category: 'Conversion',
  },
  {
    id: 'uuid-v4',
    nameKey: 'tools.uuid_v4.name',
    descriptionKey: 'tools.uuid_v4.description',
    href: '/uuid/v4',
    icon: 'Fingerprint',
    category: 'Generators',
  },
  {
    id: 'uuid-v1',
    nameKey: 'tools.uuid_v1.name',
    descriptionKey: 'tools.uuid_v1.description',
    href: '/uuid/v1',
    icon: 'Fingerprint',
    category: 'Generators',
  },
  {
    id: 'uuid-v7',
    nameKey: 'tools.uuid_v7.name',
    descriptionKey: 'tools.uuid_v7.description',
    href: '/uuid/v7',
    icon: 'Fingerprint',
    category: 'Generators',
  },
  {
    id: 'guid-gen',
    nameKey: 'tools.guid.name',
    descriptionKey: 'tools.guid.description',
    href: '/guid',
    icon: 'Fingerprint',
    category: 'Generators',
  }
];
